//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OforSot.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialist
    {
        public int SpecialistId { get; set; }
        public string SpecialistLastName { get; set; }
        public string SpecialistFirstName { get; set; }
        public string SpecialistMeddleName { get; set; }
        public int PassportSeries { get; set; }
        public int PassportNumber { get; set; }
        public string PastPosition { get; set; }
        public string LastPlaceOfWork { get; set; }
        public string PlaceOfEducation { get; set; }
        public int MilitaryIDId { get; set; }
        public int GovernmentServiceId { get; set; }
        public int EducationId { get; set; }
        public int DisabilityId { get; set; }
        public int EmploymentHistoryId { get; set; }
        public int MedicalBookId { get; set; }
        public int SnilsId { get; set; }
    
        public virtual Disability Disability { get; set; }
        public virtual Education Education { get; set; }
        public virtual EmploymentHistory EmploymentHistory { get; set; }
        public virtual GovernmentService GovernmentService { get; set; }
        public virtual MedicalBook MedicalBook { get; set; }
        public virtual MilitaryID MilitaryID { get; set; }
        public virtual Snils Snils { get; set; }
    }
}
